version: "3.9"

services:

  micronaut-heroku-demo:
    build:
      context: ../micronaut-heroku-demo
    environment:
      - DATABSE_HOST=postgres-server
      - DATABSE_PORT=5432
      - DATABSE_NAME=postgres
      - DATABSE_USERNAME=postgres
      - DATABSE_PASSWORD=password
    ports:
      - '8080:8080'
    depends_on:
      - postgres-server

  postgres-server:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: {}